### ISSUE TITLE
Error Music Player

### ISSUE THREAD

**Issue by flippydippy** [aranajuan/whatsappAudioAutoPlay#2]
it does not auto play voice messages. It shows error Music player: file not found:/ storage/emulated/0/%REPFILES

how to point it to the right file? this is my first time working with tasker

**Comment by aranajuan** [comment]
how is set this arg?
<Str sr="arg0" ve="3">WhatsApp/Media/WhatsApp Voice Notes</Str>

check if tasker can read (permisions) this path if you have android 6+

i think you should check this line too 
<Str sr="arg1" ve="3">*.aac</Str>, i noticed that format have been changed to .OPUS (i dont know if tasker wil be able open this kind of files)

**Comment by aranajuan** [comment]
im closing it. please reopen if you need to.
